### PR TITLE
[cpplint] Fix unit tests for closing namespace comments

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Amends #52.

- - -
This change is [Reviewable](https://reviewable.io/reviews/RobotLocomotion/styleguide/53)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@rpoyner-tri for all reviews, please.

In #52, I forgot that this repository doesn't run CI.  The https://github.com/RobotLocomotion/drake/pull/19277 points out that I forgot to update the unit tests for the revised rule.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/styleguide/53)* status: LGTM missing from assignee rpoyner-tri(platform), needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/RobotLocomotion/styleguide/53#-:-NTtwFqW2QBwd60_GM1q:bnfp4nl)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
:lgtm: for extra stampiness.

**Pull request merged**
