### PR TITLE
pyguide: Mention Napoleon

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
README: Add links to online rendered docs

Per review comment here:
https://github.com/robotlocomotion/drake/pull/14144#pullrequestreview-498625067

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@ggould-tri for review please.

I don't think we need multiple reviewers here, because this is just a reference for the existing conventions.
I can certainly make an announcement in Drake Slack, `#general` and `#platform_review`.

I've also briefly checked #34, and it doesn't look like it has `pyguide` updates.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-:-MIP_4Rq2U5NLIOtj4DU:b-u3v13e)* status: LGTM missing from assignee ggould-tri(platform), needs at least two assigned reviewers (waiting on @ggould-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:  This is just a clarification of the existing situation so I don't think it needs much review.  An announcement in platform-review is probably fine.

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-:-MIPbz4I1Zn7Ym69qwEw:b-g4nx7v)* status: needs at least two assigned reviewers

**Review by EricCousineau-TRI — COMMENTED** [review]
Looks like it wants 2x reviews:
+@jwnimmer-tri might you be able to review this one? If not, I can find another victim!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-:-MIPdujd87sNYgfBlepD:b-xbvauw)* status: LGTM missing from assignee jwnimmer-tri(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-:-MIQ7EuhE_kJ82HLePOK:bnfp4nl)* status: 3 unresolved discussions (waiting on @EricCousineau-TRI)

___
*[pyguide.md, line 1626 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5-Qv9Y5yQU6mV8DD:-MIQ5-Qv9Y5yQU6mV8DE:b-knnu8s) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1626)):*
> ```Markdown
> `pydrake` documentation uses Sphinx to generate documentation
> (see Drake's [Documentation Generation Instructions](https://drake.mit.edu/documentation_instructions.html)),
> and uses the Sphinx Napoleon plugin to process Google-style docstrings\*.
> ```

FYI I hate footnotes in general, in any media, and especially when we use `*` multiple times on one webpage for different notes.  Anything worth saying is worth saying inline.
___
*[pyguide.md, line 1627 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5FAx0ANEaYCa4SFw:-MIQ5FAy-dc3DMvnqXFZ:bf1qkuk) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1627)):*
> ```Markdown
> (see Drake's [Documentation Generation Instructions](https://drake.mit.edu/documentation_instructions.html)),
> and uses the Sphinx Napoleon plugin to process Google-style docstrings\*.
> <br/> <br>
> ```

nit I have no idea why the first `br` is self-closed (`/>`) but the second one is left open (`>`)?
___
*[pyguide.md, line 1628 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ71Ns-9RyF27K9S2E:-MIQ71Ns-9RyF27K9S2F:bisp3n7) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1628)):*
> ```Markdown
> and uses the Sphinx Napoleon plugin to process Google-style docstrings\*.
> <br/> <br>
> This guide itself
> ```

nit We might as well reflow this paragraph to fit on one less line?
___
*[pyguide.md, line 1634 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5Sg07l7FJ7OHy893:-MIQ5Sg07l7FJ7OHy894:b-q2dqm7) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1634)):*
> ```Markdown
>

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35)* status: 4 unresolved discussions, needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[README.md, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MWRvXXG2qJ8KqcjZ41t:-MWRvXXH9ntRMVNrKjaY:b8fkblf) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/README.md#L49)):*
> ```Markdown
> [rendered online](https://drake.mit.edu/styleguide/pyguide.html)
> 
> \* *These docs must be generated to preview locally.*
> ```

nit Per https://github.com/RobotLocomotion/drake/pull/14811, I intend to change the preview workflow.  I am still OK merging this change, but we'll probably want to revisit this section again after 14811 lands.  OK to dismiss.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[pyguide.md, line 1626 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5-Qv9Y5yQU6mV8DD:-MWWPd_D4G51E8gTC6Ns:bp7bd8y) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1626)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI I hate footnotes in general, in any media, and especially when we use `*` multiple times on one webpage for different notes.  Anything worth saying is worth saying inline.
</blockquote></details>

Done. Removed footnote given maintainability defect.
___
*[pyguide.md, line 1627 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5FAx0ANEaYCa4SFw:-MWWPb893XiNY8wD4Ri3:b-dx4vrh) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1627)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I have no idea why the first `br` is self-closed (`/>`) but the second one is left open (`>`)?
</blockquote></details>

Done. Removed double-break for now.
___
*[pyguide.md, line 1628 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ71Ns-9RyF27K9S2E:-MWWPaVtAyJv5PKdVUFy:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1628)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit We might as well reflow this paragraph to fit on one less line?
</blockquote></details>

Done.
___
*[pyguide.md, line 1634 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5Sg07l7FJ7OHy893:-MWWPRjL4AhRNnvszRlj:b5jqlh4) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1634)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

There is no way we're going to be able to keep this up to date in a separate repository here.  The versioning facts are maintained in Drake.  If we care about summarizing and hyperlinking to the correct revision of them, then that information should live in `documentation_generation_instructions.rst` with cross-references to the relevant parts of the build system, and can be a citation here.
</blockquote></details>

Done. (Removed for now!)
___
*[README.md, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MWRvXXG2qJ8KqcjZ41t:-MWWPTHq34kGEkF9B8Xt:bpnqi8q) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/README.md#L49)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Per https://github.com/RobotLocomotion/drake/pull/14811, I intend to change the preview workflow.  I am still OK merging this change, but we'll probably want to revisit this section again after 14811 lands.  OK to dismiss.
</blockquote></details>

Done. Can remove if timing is weird, or feel free for 14811 to block this PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[pyguide.md, line 1634 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5Sg07l7FJ7OHy893:-MWWPo1M7IQujEnKYyIE:b-sv0pp5) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1634)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. (Removed for now!)
</blockquote></details>

OK Er, well, done in terms of removing drake versioning. Can remove this and move to Drake if you still want.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @ggould-tri and @jwnimmer-tri)

___
*[pyguide.md, line 1634 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5Sg07l7FJ7OHy893:-MWWPt_cAEPgsaW7cn6B:blpi90w) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1634)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

OK Er, well, done in terms of removing drake versioning. Can remove this and move to Drake if you still want.
</blockquote></details>

"this" => link to 1.6.7 sphinx docs

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35)* status: needs at least two assigned reviewers (waiting on @EricCousineau-TRI)

___
*[pyguide.md, line 1634 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MIQ5Sg07l7FJ7OHy893:-MWWRPQpAvSlfKvhQQvb:b-in0azd) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/pyguide.md#L1634)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

"this" => link to 1.6.7 sphinx docs
</blockquote></details>

OK It is a little brittle to hard-code the Ubuntu 18.04 version of Sphinx here, but I don't have a better answer.  We can revise later if we find one.  (Nixing the Drake versioning comment was good enough.)
___
*[README.md, line 49 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-MWRvXXG2qJ8KqcjZ41t:-MWWQi2BDjJ9zwKHDE4o:b-ra74ya) ([raw file](https://github.com/robotlocomotion/styleguide/blob/34f0253595f0dacb47231d652c1bd970698f7aa6/README.md#L49)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Done. Can remove if timing is weird, or feel free for 14811 to block this PR.
</blockquote></details>

Fine by me.

**Review by EricCousineau-TRI — COMMENTED** [review]
Hm... +@jwnimmer-tri ... since reviewable doesn't think you're assigned?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/35#-:-MWWSYmx9LQTcrVQKMNT:b-k22w3y)* status: :shipit: complete! all discussions resolved, LGTM from assignees ggould-tri(platform),jwnimmer-tri(platform) (waiting on @EricCousineau-TRI)

**Pull request merged**
