### PR TITLE
Update std::hash advice to require hash_append

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Relates RobotLocomotion/drake#7357.

Preview available at [jwnimmer-tri/styleguide/cppguide.html#std_hash](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/8322c48b6e631257f18e2d9d2fd9ebebea82e6f3/cppguide.html#std_hash).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/3)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-KxZLSIQiLE4dOcu9LI-:-KxZLSIQiLE4dOcu9LI0:b5u08ks) (no related file):*
RobotLocomotion/drake#7357 should merge first.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3)*

**Comment by soonho-tri** [comment]
:lgtm: (except that http://drake.mit.edu/doxygen_cxx/group__hash__append.html is not alive yet).

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-KxiTvS_KLOq_gJ7HTCS:bacvitj)*

**Comment by soonho-tri** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3)*

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI +@sammy-tri +@SeanCurtis-TRI +@ggould-tri +@sherm1 +@RussTedrake.

I think this feature is basically ready now.  Adding all platform reviewers to sign-off on the cppguide changes.

**Comment by sherm1** [comment]
:lgtm:, pending 7357

---

Reviewed 1 of 1 files at r1, 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-L-smLzsrToCIvepkoSW:b-in7y8k)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[cppguide.html, line 4115 at r2](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-L05O7Id4MylrpC5QAqg:-L05O7Ieck4WNTbMfBj2:b-6q6fyf) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f9ee3f921ecda09dfdac6d886f4eda8d82dde0ee/cppguide.html#L4115)):*
> ```HTML
> <code>drake::DefaultHash</code>.</p>
> </span>
>   
> ```

BTW minor nit Extra leading whitespace

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-L05UX1pItiK4XoPPP8I:bnfp4nl)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-L05hZIiy0rtLk-fNDr2:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-L06DbuaHS8ADAFlq2PG:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-L06GUC4h_Hs2Ps0s6So:bnfp4nl)*

**Comment by SeanCurtis-TRI** [comment]
D'oh!  How am I missing.  :LGTM:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/3#-:-L0Fw9AgQQ79C353lQR6:b-t1vwkx)*

**Pull request merged**
