### PR TITLE
cpplint/IWYU: Add atomic, bitset, complex and initializer_list

### PR DESCRIPTION
**Pull request by m-chaturvedi**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/27)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
To test this PR: https://github.com/RobotLocomotion/drake/pull/12768

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/27)* status: 1 unresolved discussion, platform LGTM missing (waiting on @m-chaturvedi)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/27#-M110aeH96tAtgMH79uv:-M110aeH96tAtgMH79uw:blf5fgu) (no related file):*
Regarding the unit test, I didn't realize in the last PR, but it occurred to me on this one -- does anyone (either automatically or manually) run them?  If it is a manual process, where is it documented?  Or else should Drake's tools/workspace/styleguide run the unit test, perhaps?  It is declared there already, but never run AFAICT.

---

**Review by jwnimmer-tri — COMMENTED** [review]
The 12768 changes (without the cpplint upgrade) will have to merge before we LGTM this PR.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/27#-:-M111JpDDsXykEZyepcp:b-f6idyz)* status: 1 unresolved discussion, platform LGTM missing (waiting on @m-chaturvedi)

**Comment by jamiesnape** [comment]
Would you like me to push a GitHub action to run the unit test? Should be trivial.

**Comment by jwnimmer-tri** [comment]
Sounds great.  Whatever the easiest solution is.

**Comment by m-chaturvedi** [comment]
The tests fail with python3.  I am fixing them.

**Comment by jwnimmer-tri** [comment]
FYI I'm happy (and probably prefer) dealing with CI + py3 porting in a new PR.  Once the Drake `#include` fixes land, we can merge this as-is.

**Comment by jamiesnape** [comment]
Agreed.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/27#-:-M11kMk78RHlAU14S38V:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

**Pull request merged**
