### PR TITLE
README: Clarify that updates from Google should be merged in, not rebased upon.

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Resolves https://github.com/RobotLocomotion/drake/issues/8638

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)

### CODE REVIEW

**Comment by EricCousineau-TRI** [comment]
+@jwnimmer-tri and +@ggould-tri for initial review, please.

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-:-LCFeRWH7YpnH3a5KAsA:b-xg55a)*

**Comment by jwnimmer-tri** [comment]
*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFf8oa14AtelXezw53:-LCFf8obAG553tS1MqMo:b-fvmhyn) (no related file):*
Can you confirm for me in Settings - Merge Button for this repo that only "Allow merge commits" is enabled now?

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFf8oa14AtelXezw53:-LCFg2At-n_Z_ApdYr7F:b-w4uzh6) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Can you confirm for me in Settings - Merge Button for this repo that only "Allow merge commits" is enabled now?
</blockquote></details>



---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-:-LCFewJQ54a_hYtsPGCO:bnfp4nl)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[README.md, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFosMc1elyAaPeA1Zn:-LCFosMdCxdNeTMAkmdV:b-77smzg) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L71)):*
> ```Markdown
>         git remote add drake git@github.com:RobotLocomotion/styleguide.git
>         git remote set-url --push drake no_push
>         git branch --set-upstream-to drake/gh-pages
> ```

This command does not work, unless I `git fetch drake` or similar between the `remote add` and `branch --set-upstream-to`.

---

*[README.md, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFpEVu3YJloaF29Idw:-LCFpEVu3YJloaF29Idx:b4fml7p) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L81)):*
> ```Markdown
> with Drake and then pull Google's changes:
> 
>     git co gh-pages
> ```

`s/co/checkout/g;` -- `co` is not something that exists.

---

*[README.md, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFrKpdC3JVT-Sw1Sh4:-LCFrKpdC3JVT-Sw1Sh5:b-6xsd86) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L82)):*
> ```Markdown
> 
>     git co gh-pages
>     git pull --rebase
> ```

I will need some f2f help with you here to understand the what and why of this line.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)*

**Comment by EricCousineau-TRI** [comment]
Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---

*[README.md, line 71 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFosMc1elyAaPeA1Zn:-LDMwfpO5DZHWS0OV_br:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L71)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This command does not work, unless I `git fetch drake` or similar between the `remote add` and `branch --set-upstream-to`.
</blockquote></details>

Done.

---

*[README.md, line 81 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFpEVu3YJloaF29Idw:-LDMwfcl61kbiKY0S3_U:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L81)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

`s/co/checkout/g;` -- `co` is not something that exists.
</blockquote></details>

Done.

---

*[README.md, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFrKpdC3JVT-Sw1Sh4:-LDMwaN13POQoS4c83AV:b-m3titz) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I will need some f2f help with you here to understand the what and why of this line.
</blockquote></details>

Was thinking about a development workflow, but realized that this doesn't really make much sense. Changed to a non-rebase `pull`.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)*

**Comment by jwnimmer-tri** [comment]
This seems good now, but I want to re-test it locally from scratch again.  I'll try to get to that soon.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFrKpdC3JVT-Sw1Sh4:-LDNcdqvBcmeqYRFlI0f:b-59s50t) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L82)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Was thinking about a development workflow, but realized that this doesn't really make much sense. Changed to a non-rebase `pull`.
</blockquote></details>

BTW Should this one be `--ff-only`?  I would expect so.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-:-LDNclQE7VPTuuquII6W:b-yrwa74)*

**Comment by jwnimmer-tri** [comment]
Tested locally a-ok.

:lgtm: modulo discussions.

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[README.md, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LDnQKaRAdSSwJeVwHPV:-LDnQKaS2ErFxtoWKXFK:b2hfpxr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/50ad498760f2ba77fadf5f814716f679668d63fc/README.md#L76)):*
> ```Markdown
>  * Add a "google" remote for the Drake styleguide:
> 
>         git remote add google git@github.com:google/styleguide.git
> ```

FYI Both here and the drake remote above could use `https://` for a read-only clone, since we should not be pushing to them anyway?

---

*[README.md, line 86 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LDnQfsJBMVUdsTm3XZ1:-LDnQfsJBMVUdsTm3XZ2:bd46wtf) ([raw file](https://github.com/robotlocomotion/styleguide/blob/50ad498760f2ba77fadf5f814716f679668d63fc/README.md#L86)):*
> ```Markdown
>     git checkout -b **NEW_BRANCH_NAME**
>     git pull google gh-pages
>     **RESOLVE CONFLICTS**
> ```

Here we needs a `git commit` after resolving conflicts in the editor (iff there were conflicts).

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-:-LDnQtZcEywuOOxnCOwy:benvtjh)*

**Comment by jwnimmer-tri** [comment]
@EricCousineau-TRI ping.

**Comment by ggould-tri** [comment]
#9060 indicates that we need to un-stall this.  @ericcousineau-tri  ?

---

Review status: 2 unresolved discussions, platform LGTM from [ggould-tri, jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-:-LFwETUuCg90Lb54ETzC:b-ug66ll)*

**Comment by EricCousineau-TRI** [comment]
Review status: 2 unresolved discussions, platform LGTM from [ggould-tri, jwnimmer-tri]

---

*[README.md, line 82 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LCFrKpdC3JVT-Sw1Sh4:-LFxdqLHCI_P5g5F17km:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/1afa677f01c4c8a2ea1ca247e039fe1d24a0b392/README.md#L82)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

BTW Should this one be `--ff-only`?  I would expect so.
</blockquote></details>

Done.

---

*[README.md, line 76 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LDnQKaRAdSSwJeVwHPV:-LFxdpL-83kBSilWrCMf:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/50ad498760f2ba77fadf5f814716f679668d63fc/README.md#L76)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

FYI Both here and the drake remote above could use `https://` for a read-only clone, since we should not be pushing to them anyway?
</blockquote></details>

Done.

---

*[README.md, line 86 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/10#-LDnQfsJBMVUdsTm3XZ1:-LFxdryg7CU5KwS06kfi:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/50ad498760f2ba77fadf5f814716f679668d63fc/README.md#L86)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Here we needs a `git commit` after resolving conflicts in the editor (iff there were conflicts).
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)*

**Comment by ggould-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: 2 unresolved discussions, platform LGTM from [ggould-tri, jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)*

**Comment by jwnimmer-tri** [comment]
Reviewed 1 of 1 files at r3.
Review status: :shipit: complete! all discussions resolved, platform LGTM from [ggould-tri, jwnimmer-tri]

---



*Comments from [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/10)*

**Review by jwnimmer-tri — APPROVED** [review]

**Comment by jwnimmer-tri** [comment]
This repo is erroneously set up to require GH review, instead of only just reviewable.  I went ahead and applied my LGTM to GH review as well.

**Pull request merged**
