### PR TITLE
Add some recent clarifications

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For a preview [click here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/clarify-2022-07/cppguide.html).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
*[`cppguide.html` line 393 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-N9-G5ZTDJyF8O2stxWr:-N9-G5ZTDJyF8O2stxWs:b-r0ffb) ([raw file](https://github.com/robotlocomotion/styleguide/blob/66f7eb0dec34b47e854d0b9f2e0c0fcd4f0ce850/cppguide.html#L393)):*
> ```HTML
> <h3 id="Inline_Functions">Inline Functions</h3>
> 
> WIP
> ```

Working

In particular, DRAKE_DEMAND or DRAKE_THROW_UNLESS is not on its own a reason to move a function definition into the cc file.  We have carefully tuned those functions to have a reasonable impact on object code, even when inlined.

\CC @rpoyner-tri FYI

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NF97ROr7jS5KBqymJnA:bmxilld)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`cppguide.html` line 1561 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NF940EQ3u_qwN1UnHvE:-NF940ER0MYEXC-Dok-u:b-m41s22) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f952abc81f346a7c48d90a6ebe04f0988d0dfaea/cppguide.html#L1561)):*
> ```HTML
> declaring and/or deleting the appropriate operations in the <code>public</code>
> section of the declaration
> <span class="drake">except in the case of structs with no private fields</span>.
> ```

nit: Two thoughts:

1. It might be helpful to others if some motivation were clearly given. Perhaps some kind of cross reference to "Structs vs. Classes"? (It seems unlikely that someone reading this here, will page down to the next section to discover the explanation.)
2. Extending the example below with such a struct and a comment saying, "this is ok", would be good for the cargo culting crew.
___
*[`cppguide.html` line 6662 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NF96RFA3UJyjrf7mCY8:-NF96RFA3UJyjrf7mCY9:b-ltcggk) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f952abc81f346a7c48d90a6ebe04f0988d0dfaea/cppguide.html#L6662)):*
BTW I wrestled long and hard with this sentence. While I can see that it can be interpreted as you intend, I feel it easily allows misapprehension. I appreciate how succinct it is, but would recommend a slight tweak:

> Code reviews within that folder should not __*comment on whitespace; CI will catch all such defects*__.

(Getting rid of "nitpick" and "choices", as the former has strong pejorative connotations and the latter is an illusion, while adding an explicit salve to the reader's conscience.)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:; This is all very clear and makes our practices much more precise.

> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NF9A2Ur2VCrzIiPTM-U:byhz6f3)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50)* status: 2 unresolved discussions, needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @ggould-tri and @SeanCurtis-TRI)

___
*[`cppguide.html` line 1561 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NF940EQ3u_qwN1UnHvE:-NF9EUpo9TDSm_p21j4u:b-dl894d) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f952abc81f346a7c48d90a6ebe04f0988d0dfaea/cppguide.html#L1561)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Two thoughts:

1. It might be helpful to others if some motivation were clearly given. Perhaps some kind of cross reference to "Structs vs. Classes"? (It seems unlikely that someone reading this here, will page down to the next section to discover the explanation.)
2. Extending the example below with such a struct and a comment saying, "this is ok", would be good for the cargo culting crew.
</blockquote></details>

(1) I do actually except users of this document to read each section in full.  I added a hint here, though.

(2) Right!  I'd meant to do that, but it slipped away from me.
___
*[`cppguide.html` line 6662 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NF96RFA3UJyjrf7mCY8:-NF9BByj9eH8trlMXxjr:b-hujry2) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f952abc81f346a7c48d90a6ebe04f0988d0dfaea/cppguide.html#L6662)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I wrestled long and hard with this sentence. While I can see that it can be interpreted as you intend, I feel it easily allows misapprehension. I appreciate how succinct it is, but would recommend a slight tweak:

> Code reviews within that folder should not __*comment on whitespace; CI will catch all such defects*__.

(Getting rid of "nitpick" and "choices", as the former has strong pejorative connotations and the latter is an illusion, while adding an explicit salve to the reader's conscience.)
</blockquote></details>

Hmm, I was trying to leave a little room for the inconsistent use (or non-use, or mis-use) of `// BR` still being an allowed defect.  That intention was probably too subtle, and not worth pursuing.

WDYT of this new wording?

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[`cppguide.html` line 6662 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NF96RFA3UJyjrf7mCY8:-NF9MauVDoC-BW0EaFoO:b-bvj7ym) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f952abc81f346a7c48d90a6ebe04f0988d0dfaea/cppguide.html#L6662)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Hmm, I was trying to leave a little room for the inconsistent use (or non-use, or mis-use) of `// BR` still being an allowed defect.  That intention was probably too subtle, and not worth pursuing.

WDYT of this new wording?
</blockquote></details>

Looks good to me.  :)

**Comment by jwnimmer-tri** [comment]
Tagging everyone for review, please:
+@ggould-tri
+@rpoyner-tri
+@sherm1
+@sammy-tri
+@SeanCurtis-TRI
+@xuchenhan-tri
+@EricCousineau-tri
+@RussTedrake

I'll leave this open for one week (until **2022-10-31**) for any comments, at which point I'll unassign anyone who hasn't replied.

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform),xuchenhan-tri (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @xuchenhan-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NF9bAz14VpXo0H_aRDH:bnfp4nl)* status: LGTM missing from assignees sammy-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform),xuchenhan-tri (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @xuchenhan-tri)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NF9gEmZ0DscjsTH-zBk:bnfp4nl)* status: LGTM missing from assignees sammy-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform),xuchenhan-tri (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, and @xuchenhan-tri)

**Review by xuchen-han — COMMENTED** [review]
:lgtm: 

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NFA8GdpBCjj5tMVEAGj:bg7igkv)* status: LGTM missing from assignees sammy-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, and @sammy-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50)* status: 1 unresolved discussion, LGTM missing from assignees sammy-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @xuchenhan-tri)

___
*[`cppguide.html` line 513 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NFAB9g1Ainxh9zBhtwP:-NFAB9g1Ainxh9zBhtwQ:bb7phvt) ([raw file](https://github.com/robotlocomotion/styleguide/blob/008b58dc020557607c2556ccb1037348c10fa57f/cppguide.html#L513)):*
> ```HTML
> In contrast, throwing an exception with
> <code>if (condition) { throw std::logic_error(fmt::format(...)); }</code>
> is usually a huge amount of object code as should not appear inline.
> ```

typo



_Suggestion:_
```HTML
and
```

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NFB1qiv8pzaJfGZrdpV:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, and @RussTedrake)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: with small nit

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NFApeZFDCglOujC4_ZK:b-qo29t7)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @ggould-tri, @jwnimmer-tri, @rpoyner-tri, and @RussTedrake)

___
*[`cppguide.html` line 6801 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NFApm5GE51vHJHXu3FN:-NFApm5HCZBhnV1NL94D:b-d0vfxj) ([raw file](https://github.com/robotlocomotion/styleguide/blob/008b58dc020557607c2556ccb1037348c10fa57f/cppguide.html#L6801)):*
> ```HTML
> </ul>
> 
> <div class="drake">For the pydrake bindings' C++ code (in drake/bindings/...),
> ```

nit This appears repeated from above point; from reading in context, it is not clear why.

Can this be removed?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50)* status: 2 unresolved discussions, LGTM missing from assignee RussTedrake(platform) (waiting on @ggould-tri, @jwnimmer-tri, @rpoyner-tri, and @RussTedrake)

___
*[`cppguide.html` line 6801 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-NFApm5GE51vHJHXu3FN:-NFBN9eB-Bsys0r85QpW:bvzanul) ([raw file](https://github.com/robotlocomotion/styleguide/blob/008b58dc020557607c2556ccb1037348c10fa57f/cppguide.html#L6801)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit This appears repeated from above point; from reading in context, it is not clear why.

Can this be removed?
</blockquote></details>

OK Nevermind. Looked at preview, and now I see why.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/50#-:-NFJ1AUA4hs-Er8KcDZM:bnfp4nl)* status: 1 unresolved discussion (waiting on @ggould-tri and @rpoyner-tri)

**Pull request merged**
