### PR TITLE
Add CI using GitHub Actions

### PR DESCRIPTION
**Pull request by jamiesnape**
While upstream supports Python 2.7 and we are using `six`, seems like we should at least check Python 2.7. Easy to switch off if it is troublesome anyway (delete one line).

Note on macOS, Homebrew is in the process of switching from Python 3.7 to 3.8, while Apple provide 2.7 and 3.7.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/29)

### CODE REVIEW

**Comment by m-chaturvedi** [comment]
@jamiesnape: https://github.com/RobotLocomotion/styleguide/pull/28#pullrequestreview-367515128

**Comment by jamiesnape** [comment]
See https://github.com/jamiesnape/styleguide/runs/485292531.

**Comment by jamiesnape** [comment]
+@jwnimmer-tri for review.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/29#-:-M1aDwB65eAGWEHqCr-h:bnfp4nl)* status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @jamiesnape)

___
*[.github/workflows/main.yml, line 29 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/29#-M1aDUEHAJVGeybGwZpI:-M1aDUEHAJVGeybGwZpJ:b-mxgwyu) ([raw file](https://github.com/robotlocomotion/styleguide/blob/7cf1259e88eb72e2a45938b3bb5c723d0ad9d94e/.github/workflows/main.yml#L29)):*
nit

> While upstream supports Python 2.7 and we are using six, seems like we should at least check Python 2.7. Easy to switch off if it is troublesome anyway (delete one line).

I agree, but it seems like that rationale should live on in a comment here for future maintainers who might wonder about the choice.
___
*[.github/workflows/main.yml, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/29#-M1aDcKh2ga0oSCo2BMd:-M1aDcKh2ga0oSCo2BMe:b7oiejs) ([raw file](https://github.com/robotlocomotion/styleguide/blob/7cf1259e88eb72e2a45938b3bb5c723d0ad9d94e/.github/workflows/main.yml#L33)):*
> ```YAML
>           - 3.6
>           - 3.7
>           - 3.8
> ```

nit Unclear why we're testing 3.8 on macOS given that https://drake.mit.edu/developers.html#supported-configurations does not have 3.8.

**Review by jamiesnape — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/29)* status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @jamiesnape and @jwnimmer-tri)

___
*[.github/workflows/main.yml, line 33 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/29#-M1aDcKh2ga0oSCo2BMd:-M1aEHQBAST4_7Ovsu0s:b-dlwkzi) ([raw file](https://github.com/robotlocomotion/styleguide/blob/7cf1259e88eb72e2a45938b3bb5c723d0ad9d94e/.github/workflows/main.yml#L33)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit Unclear why we're testing 3.8 on macOS given that https://drake.mit.edu/developers.html#supported-configurations does not have 3.8.
</blockquote></details>

I guess I added the note at the top too late (and I will add a comment). Homebrew is gradually switching to 3.8.

**Review by jwnimmer-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/29)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

**Pull request merged**
