### PR TITLE
Merge google upstream as of 2020-05-26

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For a preview [click here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/google-merge-2020-05-26/cppguide.html).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[cppguide.html, line 1932 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ-ZYP98otDT6YRBKl6:-MJ-ZYPA0t-5Uv481rIz:buwv6hr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L1932)):*
> ```HTML
> the function into smaller and more manageable pieces.</p>
> 
> <span class="drake">
> ```

FYI Google has removed this whole section upstream.  I've resurrected it under a "span drake" for now -- leaving aside the question of whether we _want_ to use mutable references for required outputs.  If we want to enact that change, my vote is that we do it under a separate proposal and pull request.

**Review by SeanCurtis-TRI — COMMENTED** [review]
+@seancurtis-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJ2x1WQ65QMfRtOcFa_:b-l9yj1x)* status: LGTM missing from assignee SeanCurtis-TRI(platform), needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
Two minor things jumped out at me - worth a brief conversation, possibly. Otherwise, :LGTM:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJ3125h454VM2HWmcDS:bbganf7)* status: needs at least two assigned reviewers

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJ2yq5o2wWOEpJ9H0Nf:b-ugwztv) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
> ```HTML
> 
> <p class="decision"></p>
> <p>Do not use rvalue references (or apply the <code>&amp;&amp;</code>
> ```

BTW I can think of some examples in the hydroelastic code that exercise the previous "you may" guidance but would stand against this updated.

Is the swap from "you may" to "do not" something that should be "non-drake"d pending further discussion?
___
*[cppguide.html, line 2955 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2zDcJ0TEm_AxqVrxQ:-MJ2zDcJ0TEm_AxqVrxR:b15a5nr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2955)):*
> ```HTML
> <code>int64 y = int64{1} &lt;&lt; 42</code>. Do not use
> cast formats like <code>(int)x</code> unless the cast is to
> <code>void</code>. You may use cast formats like `T(x)` only when
> ```

BTW As I read this, it seems we've implicitly ok'd

```c++
(void)some_param;
```

instead of 

```c++
unused(some_param);
```

It's a *mite* confusing because it's stated so strongly and directly here, but doesn't appear in the decision.
___
*[cppguide.html, line 3942 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ30EHdDY1iKaLjoNiF:-MJ30EHe9F-I-ofhFAA4:bgrkeeo) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L3942)):*
> ```HTML
>   <a href="#Type_deduction">Type deduction</a>.</p>
> 
> <h3 id="Designated_initializers">Designated initializers</h3>
> ```

BTW Yay!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJ335aH9MQA6kdTK9ja:bgrp8vp) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW I can think of some examples in the hydroelastic code that exercise the previous "you may" guidance but would stand against this updated.

Is the swap from "you may" to "do not" something that should be "non-drake"d pending further discussion?
</blockquote></details>

It probably depends on the circumstances.  Could you link to one or a few examples that would go against the new policy?  My initial impression is that GSG's new statement of the rules is correct and we should try to obey it, but there might be good reasons not to -- some concrete code would help me form a more informed opinion.
___
*[cppguide.html, line 2955 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2zDcJ0TEm_AxqVrxQ:-MJ33yLM2S04AbCkeWLY:b7sc8ru) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2955)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW As I read this, it seems we've implicitly ok'd

```c++
(void)some_param;
```

instead of 

```c++
unused(some_param);
```

It's a *mite* confusing because it's stated so strongly and directly here, but doesn't appear in the decision.
</blockquote></details>

To be clear... your point is that the clarity of the presentation could be improved?  (Not that you think we should disallow `(void)`.)

I'm happy to improveo the text, I just want to make sure I'm headed in the right direction.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJ7RIAz2bMwyG9Sa0CM:b-36pmwc) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It probably depends on the circumstances.  Could you link to one or a few examples that would go against the new policy?  My initial impression is that GSG's new statement of the rules is correct and we should try to obey it, but there might be good reasons not to -- some concrete code would help me form a more informed opinion.
</blockquote></details>

There are a number of examples like this:

https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/surface_mesh.h#L217-L218

In the hydroelastic code. There's no real value in them being r-value references (passing by value would be sufficient and would leave the call sites untouched).

Whether or not the language disallows this comes down to the question of, does the r-value parameter, which *requires* the caller to guarantee an r-value yield superior code over a pass-by-value parameter that would allow the caller to accidentally copy data?

In retrospect, I'm inclined to leave it (and its various incarnations spread around `geometry` and `multibody` and all related to hydroleastics).  See

  - `mesh_field_linear.h` (constructor)
  - `volume_mesh.h` (constructor)
  - `hydroelastic_contact_info.h` (constructor)
___
*[cppguide.html, line 2955 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2zDcJ0TEm_AxqVrxQ:-MJ7T5hjCqEsutN2tKuE:b-88eub0) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2955)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

To be clear... your point is that the clarity of the presentation could be improved?  (Not that you think we should disallow `(void)`.)

I'm happy to improveo the text, I just want to make sure I'm headed in the right direction.
</blockquote></details>

Correct. I have no problem with allowing `(void)thing`. I'd just hope the language unambiguously went one way or the other.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

___
*[cppguide.html, line 2955 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2zDcJ0TEm_AxqVrxQ:-MJ8kDfz99PiHQcPetJF:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2955)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

Correct. I have no problem with allowing `(void)thing`. I'd just hope the language unambiguously went one way or the other.
</blockquote></details>

Done.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: needs at least two assigned reviewers (waiting on @SeanCurtis-TRI)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJ8qZb26SAsNmrOutmE:bd4lu2w) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

There are a number of examples like this:

https://github.com/RobotLocomotion/drake/blob/master/geometry/proximity/surface_mesh.h#L217-L218

In the hydroelastic code. There's no real value in them being r-value references (passing by value would be sufficient and would leave the call sites untouched).

Whether or not the language disallows this comes down to the question of, does the r-value parameter, which *requires* the caller to guarantee an r-value yield superior code over a pass-by-value parameter that would allow the caller to accidentally copy data?

In retrospect, I'm inclined to leave it (and its various incarnations spread around `geometry` and `multibody` and all related to hydroleastics).  See

  - `mesh_field_linear.h` (constructor)
  - `volume_mesh.h` (constructor)
  - `hydroelastic_contact_info.h` (constructor)

</blockquote></details>

Done.

I'm pretty sure Google is correct and we're abusing C++ in those files, but I also think that we should separate controversial policy changes from the upgrade PRs, so I've put back the weaker rule in this PR.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI
+@ggould-tri
+@rpoyner-tri
+@sammy-tri
+@sherm1
+@soonho-tri
+@RussTedrake
for review, please.

For a preview [click here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/google-merge-2020-05-26/cppguide.html).

You are invited to read this as closely or loosely as your time merits. I'll leave this open for one week (until Oct 15th) and resolve any discussions you open during that period, but then I'll plan to merge after that point. We can continue revising the guide in follow-ups as necessary.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform),sammy-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJ974BqEUDC5mbaOd1G:b-rr04w7) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
In retrospect, I realize that the code cited above doesn't conform to the old style guide language either. The only real difference is that the new language is drawing the hard line more clearly.

As such, and I regret to say this, I feel that these `drake` modifications provide no value. They don't actually *change* the content of the message here.

> Do not use, except as follows:

and

> You  may use as follows:

Have exactly the same meaning: "what follows is the list of what is allowed". The only differ in connotation.

So, since the added drake "clarification" neither changes the meaning of the text, nor justifies code that has arguably always been defective, we should probably jettison it.

(P.S. I'm still not sold on google being correct, some day I'll ask you for your thoughts on that. But it's a different conversation entirely.)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJ9MXbH8NMT0i3ojFqm:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJCbY3S7PT9FcbNfCnX:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 1873 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJC_EYU4wskwmbiGZFE:-MJC_EYU4wskwmbiGZFF:b2ox7ze) ([raw file](https://github.com/robotlocomotion/styleguide/blob/7fb354cfca9537a28c5dfb5acbc8039d29de2296/cppguide.html#L1873)):*
> ```HTML
> <span class="nondrake">
> while required (non-nullable) output and input/output parameters should
> usually be references. Generally, use <code>absl::optional</code> to represent
> ```

minor:  This (output parameters as mutable references) is the same as the FYI below; if we're retaining the mutable reference prohibitions (and I think we should) then this needs a nondrake.  And it should probably be nondrake for the duration of the discussion regardless.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJCsKm31tfuITBtJzea:bdejk22) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

In retrospect, I realize that the code cited above doesn't conform to the old style guide language either. The only real difference is that the new language is drawing the hard line more clearly.

As such, and I regret to say this, I feel that these `drake` modifications provide no value. They don't actually *change* the content of the message here.

> Do not use, except as follows:

and

> You  may use as follows:

Have exactly the same meaning: "what follows is the list of what is allowed". The only differ in connotation.

So, since the added drake "clarification" neither changes the meaning of the text, nor justifies code that has arguably always been defective, we should probably jettison it.

(P.S. I'm still not sold on google being correct, some day I'll ask you for your thoughts on that. But it's a different conversation entirely.)
</blockquote></details>

Before making the drake/nondrake edit, I looked at the old text and interpreted "you may use [as follows]" as specifically encouraging to some good uses, but remaining _silent_ on other uses - it does not necessarily imply they are verboten.

Remember my goal in this thread is to defer any controversy to follow-up PRs.  Because I think a valid reading of the prior text was to allow novel uses, I think it's okay to have drake/nondrake like this.  However, if you're comfortable that the new text alone is uncontroversial, then I'll undo my edit.  LMK.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 1873 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJC_EYU4wskwmbiGZFE:-MJCtp9g8iw8uXv2UnvQ:bcbwglj) ([raw file](https://github.com/robotlocomotion/styleguide/blob/7fb354cfca9537a28c5dfb5acbc8039d29de2296/cppguide.html#L1873)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

minor:  This (output parameters as mutable references) is the same as the FYI below; if we're retaining the mutable reference prohibitions (and I think we should) then this needs a nondrake.  And it should probably be nondrake for the duration of the discussion regardless.
</blockquote></details>

I _think_ I already have "nondrake" on the correct slices of sentences here?  Or maybe I'm misunderstanding you.  Could you recheck and/or be more specific?

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 1873 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJC_EYU4wskwmbiGZFE:-MJCukW2B_tgFZce1W6v:b123cfq) ([raw file](https://github.com/robotlocomotion/styleguide/blob/7fb354cfca9537a28c5dfb5acbc8039d29de2296/cppguide.html#L1873)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I _think_ I already have "nondrake" on the correct slices of sentences here?  Or maybe I'm misunderstanding you.  Could you recheck and/or be more specific?
</blockquote></details>

Oh, sure enough.  I somehow missed that in tracking the spans.

**Review by SeanCurtis-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJCvfIq4-jpoPNHeYcq:btjppd4) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Before making the drake/nondrake edit, I looked at the old text and interpreted "you may use [as follows]" as specifically encouraging to some good uses, but remaining _silent_ on other uses - it does not necessarily imply they are verboten.

Remember my goal in this thread is to defer any controversy to follow-up PRs.  Because I think a valid reading of the prior text was to allow novel uses, I think it's okay to have drake/nondrake like this.  However, if you're comfortable that the new text alone is uncontroversial, then I'll undo my edit.  LMK.
</blockquote></details>

I see no controversy in the new text alone and favor simplifying our diff.  :)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 2508 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-MJ2yq5o2wWOEpJ9H0Ne:-MJCwaQ00ya3Izh5rzX0:b-zcrezk) ([raw file](https://github.com/robotlocomotion/styleguide/blob/b8538e057ad1df839745da6cbd649234b871a439/cppguide.html#L2508)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

I see no controversy in the new text alone and favor simplifying our diff.  :)
</blockquote></details>

OK Reverted.  Reviewable actually shows it as a strikethrough r5 though, so it's not showing up new here.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJCxkdM13ckOkl8L2tG:bmxilld)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJDI9Y3DAMCLgqTJJsd:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, and @sherm1)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJE9tnB4KwK9wVKj116:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, and @sammy-tri)

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/37#-:-MJU42l6DJJzeuwFYpOI:bnfp4nl)* status: LGTM missing from assignees EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, and @sammy-tri)

**Comment by jwnimmer-tri** [comment]
The review deadline has expired, I'm merging now. I am happy to adjust to late feedback in a separate PR.

-@EricCousineau-TRI -@RussTedrake

**Pull request merged**
