### PR TITLE
Add some recent clarifications

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For a preview [click here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/testing-for-exceptions/cppguide.html).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)

### CODE REVIEW

**Review by sherm1 — COMMENTED** [review]
:lgtm:, thanks

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me1_aP73r86u93cJNpc:b-1gl4aa)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me1aKW48nE87AnLgyvh:bnfp4nl)* status: needs platform reviewer assigned, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI
+@RussTedrake
+@SeanCurtis-TRI
+@rpoyner-tri
+@sammy-tri
+@soonho-tri
for review, please.

You are invited to read this as closely or loosely as your time merits. I'll leave this open for one week (until July 14th) and resolve any discussions you open during that period, but then I'll plan to merge after that point. We can continue revising the guide in follow-ups as necessary.

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, @SeanCurtis-TRI, and @soonho-tri)

___
*[cppguide.html, line 2635 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me1pbxi4WaHhLKzCi3l:-Me1pbxi4WaHhLKzCi3m:b373nre) ([raw file](https://github.com/robotlocomotion/styleguide/blob/9e405642bb1f8e78c218f13fe616228cc5a07763/cppguide.html#L2635)):*
> ```HTML
> 
> <p>See also <a href="Use of const">#Use_of_const</a> for an explanation of
> whether arguments passed by-value may not be marked <code>const</code>.</p>
> ```

nit: "whether arguments passed by-value may not be marked const" sounds awkward. Should this be something like "why arguments passed by value may not be marked const" or "whether or not arguments passed by value may be marked const"?

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @SeanCurtis-TRI, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 2635 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me1pbxi4WaHhLKzCi3l:-Me1reix9fqTPRECZPIp:b-362uhr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/9e405642bb1f8e78c218f13fe616228cc5a07763/cppguide.html#L2635)):*
<details><summary><i>Previously, sammy-tri (Sam Creasey) wrote…</i></summary><blockquote>

nit: "whether arguments passed by-value may not be marked const" sounds awkward. Should this be something like "why arguments passed by value may not be marked const" or "whether or not arguments passed by value may be marked const"?
</blockquote></details>

Oops, you're right.  I rewrote this sentence many times and apparently ended up with word salad by the end.  I've nixed the "not".

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me1sr_Q3hBL1_xIozH4:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @SeanCurtis-TRI, and @soonho-tri)

**Comment by jwnimmer-tri** [comment]
___
*[cppguide.html, line 4908 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me2EOKl2WOu5UJFMs0B:-Me2EOKmDWKGXthq0RF0:b-flguq6) ([raw file](https://github.com/robotlocomotion/styleguide/blob/462ea231eef8d6e10457122c0beb59911bc616b4/cppguide.html#L4908)):*
> ```HTML
> 
> <p>Even in the case of class data members (whether static or non-static),
> never add a trailing underscore to a <code>kMixedCase</code> name.</p>
> ```

FYI https://github.com/google/styleguide/issues/307 is upstream's (concurring) response to this same question.

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me2FMiH4HFJHv0Mocf5:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @SeanCurtis-TRI, and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

___
*[cppguide.html, line 2634 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me2NiZN4VlY2WmVuquq:-Me2NiZN4VlY2WmVuqur:b-72qz1s) ([raw file](https://github.com/robotlocomotion/styleguide/blob/462ea231eef8d6e10457122c0beb59911bc616b4/cppguide.html#L2634)):*
>  <a href="Use of const">#Use_of_const</a>

=> `<a href="#Use_of_const">Use of const</a>`

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me2PrDsBFEvA4w3BCvI:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: 1 unresolved discussion, LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @SeanCurtis-TRI, and @soonho-tri)

___
*[cppguide.html, line 2634 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me2NiZN4VlY2WmVuquq:-Me2R-cl0WhnUSHuLL1E:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/462ea231eef8d6e10457122c0beb59911bc616b4/cppguide.html#L2634)):*
<details><summary><i>Previously, soonho-tri (Soonho Kong) wrote…</i></summary><blockquote>

>  <a href="Use of const">#Use_of_const</a>

=> `<a href="#Use_of_const">Use of const</a>`
</blockquote></details>

Done.

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

**Review by ggould-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignees rpoyner-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, and @SeanCurtis-TRI)

___
*[cppguide.html, line 2635 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me1pbxi4WaHhLKzCi3l:-Me5-P95-5YuUZNauxxR:bg0tdnx) ([raw file](https://github.com/robotlocomotion/styleguide/blob/9e405642bb1f8e78c218f13fe616228cc5a07763/cppguide.html#L2635)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Oops, you're right.  I rewrote this sentence many times and apparently ended up with word salad by the end.  I've nixed the "not".
</blockquote></details>

Very minor quibble:  "may be declared const" might be slightly clearer than "may be marked const" since the rule applies only to the point of declaration.

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me6atlL3ktIHFpqeEtM:bnfp4nl)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @RussTedrake, and @SeanCurtis-TRI)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @RussTedrake, and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-Me79GDoDGDz5miJ8izB:bmxilld)* status: 3 unresolved discussions, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @RussTedrake)

___
*[cppguide.html, line 2623 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me77wVK5sWxqBphzZUj:-Me77wVK5sWxqBphzZUk:b-drv1w3) ([raw file](https://github.com/robotlocomotion/styleguide/blob/e4684db8cf0687fa4bbb52baa8d3b1498d86209f/cppguide.html#L2623)):*
> ```HTML
> </p>
> 
> <h4 id="Pass_By_Value_Primitives">Pass by Value: Primitives</h4>
> ```

BTW When reasoning about the scalar `T`, a developer might have `T = double` in mind and think they should pass `T` by value. However, the common practice is to pass `T` by const reference because of the arbitrary size of the supported scalar types.  Worth making that distinction here?
___
*[cppguide.html, line 2682 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me78V_X1NPV6O0OFkUc:-Me78V_X1NPV6O0OFkUd:b-9xfxjy) ([raw file](https://github.com/robotlocomotion/styleguide/blob/e4684db8cf0687fa4bbb52baa8d3b1498d86209f/cppguide.html#L2682)):*
> ```HTML
>   subclass, but we don't need to document it in the API for this purpose.</li>
>   </ul>
> ```

BTW How do you feel about suggesting that a well-phrased exception message is probably worth more than the type. And, furthermore, it is well paired with the `DRAKE_EXPECT_THROWS_MESSAGE` in the unit test (still ignoring specific exception type).
___
*[cppguide.html, line 4749 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me78rQc6yms5Fm32fhm:-Me78rQc6yms5Fm32fhn:bmzh7kd) ([raw file](https://github.com/robotlocomotion/styleguide/blob/e4684db8cf0687fa4bbb52baa8d3b1498d86209f/cppguide.html#L4749)):*
> ```HTML
>   (one letter, upper-case); it is not mandatory to downcase it or give it a
>   more verbose name. However, even if a variable name is capitalized to
>   match common conventions, we still use underscores ("snake case") to delimit
> ```

BTW Huzzah!

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, and @SeanCurtis-TRI)

___
*[cppguide.html, line 2623 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me77wVK5sWxqBphzZUj:-Me7IqDN0moJekF9JLCY:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/e4684db8cf0687fa4bbb52baa8d3b1498d86209f/cppguide.html#L2623)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW When reasoning about the scalar `T`, a developer might have `T = double` in mind and think they should pass `T` by value. However, the common practice is to pass `T` by const reference because of the arbitrary size of the supported scalar types.  Worth making that distinction here?
</blockquote></details>

Done.
___
*[cppguide.html, line 2682 at r5](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-Me78V_X1NPV6O0OFkUc:-Me7Ja5L9FFD7Rrq-sRb:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/e4684db8cf0687fa4bbb52baa8d3b1498d86209f/cppguide.html#L2682)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW How do you feel about suggesting that a well-phrased exception message is probably worth more than the type. And, furthermore, it is well paired with the `DRAKE_EXPECT_THROWS_MESSAGE` in the unit test (still ignoring specific exception type).
</blockquote></details>

Done.

**Review by rpoyner-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @RussTedrake)

**Review by soonho-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by sammy-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[cppguide.html, line 4913 at r6](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-MeQdrne4v0aAdKGMqdb:-MeQdrne4v0aAdKGMqdc:bvfi696) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3138325360fb6540f97cb486be2abb20cf08f991/cppguide.html#L4913)):*
> ```HTML
> template &lt;typename T, int kNumStages = 2&gt;
> class RadauIntegrator { ... };
> </pre>
> ```

An interesting variation of this showed up in #15334 :
```
template<int foo>
class Bar {
 public:
  constexpr static int kFoo = foo;
 ...
}
```
Under this rule this smells prohibited, but in fact since the constant is only accessible via an instantiation-scoped name (`Bar<7>::kFoo`) I think it's probably fine?  In any case since it's demonstrably a desire line in current code, we should probably put that case with a good or bad designation here.

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI and @ggould-tri)

___
*[cppguide.html, line 4913 at r6](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-MeQdrne4v0aAdKGMqdb:-MeQsct09kzScRkcvxSz:bhd33ir) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3138325360fb6540f97cb486be2abb20cf08f991/cppguide.html#L4913)):*
<details><summary><i>Previously, ggould-tri wrote…</i></summary><blockquote>

An interesting variation of this showed up in #15334 :
```
template<int foo>
class Bar {
 public:
  constexpr static int kFoo = foo;
 ...
}
```
Under this rule this smells prohibited, but in fact since the constant is only accessible via an instantiation-scoped name (`Bar<7>::kFoo`) I think it's probably fine?  In any case since it's demonstrably a desire line in current code, we should probably put that case with a good or bad designation here.
</blockquote></details>

It's prohibited under my understanding of the rule.  The name does not refer to a program-wide constant, so it cannot be kMixedCase.  `Bar<quux>::kFoo` takes on a different value depending on what `quux` was.

I don't want to drown in examples, so I'm not particularly inclined to call it out here.

**Review by ggould-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45)* status: LGTM missing from assignee EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI)

___
*[cppguide.html, line 4913 at r6](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-MeQdrne4v0aAdKGMqdb:-MeRAFXe9cVwLvTYwIYb:bwllhwu) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3138325360fb6540f97cb486be2abb20cf08f991/cppguide.html#L4913)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

It's prohibited under my understanding of the rule.  The name does not refer to a program-wide constant, so it cannot be kMixedCase.  `Bar<quux>::kFoo` takes on a different value depending on what `quux` was.

I don't want to drown in examples, so I'm not particularly inclined to call it out here.
</blockquote></details>

That seems reasonable to me, albeit not my intuitive understanding of the rule.
By that reasoning, `kFoo` should be named `foo`, then (unless "constant" in https://drake.mit.edu/styleguide/cppguide.html#Access_Control is also interpreted by this same rule, in which case the existence of public member constants in template classes is prohibited outright, but I think that result would be unnecessarily unfriendly).

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-:-MeS0uSgB-_4mKHIGMaQ:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI)

**Comment by jwnimmer-tri** [comment]
___
*[cppguide.html, line 4899 at r6](https://reviewable.io/reviews/robotlocomotion/styleguide/45#-MeTSUbb1k4nUSsiIrYB:-MeTSUbd1kq-KG4B7rDf:b3pjx8r) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3138325360fb6540f97cb486be2abb20cf08f991/cppguide.html#L4899)):*
FYI For the record, the GSG already had a little buried advice that confirms this rule, although it was hard to find: 

> ... non-type template parameters should follow the rules for variable names [hyperlinks to snake_case variable names] ...

-- https://drake.mit.edu/styleguide/cppguide.html#General_Naming_Rules

**Pull request merged**
