### PR TITLE
Explicitly document acceptance of never_destroyed

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Preview available at [jwnimmer-tri/styleguide/cppguide.html#Static_and_Global_Variables](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/2716be7ff3a92b33e64c392ff6291146cea9bfa0/cppguide.html#Static_and_Global_Variables).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/5)

### CODE REVIEW

**Comment by SeanCurtis-TRI** [comment]
:LGTM: Remind me to have a conversation with you at the beginning of next week regarding a singleton class and a function static `weak_ptr`. It's very relevant to this subject.

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5WulBIiC03VpnvyjiG:bwqdv9y)*

**Comment by soonho-tri** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5WbxIrIKCnrNYa2N2V:bnfp4nl)*

**Comment by EricCousineau-TRI** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5X9Invoc6SKixfpv1R:bnfp4nl)*

**Comment by sherm1** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5XbA3bsQToSmSaGzy5:bnfp4nl)*

**Comment by sammy-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5YqrO08k7fwbL0qHoU:bnfp4nl)*

**Comment by RussTedrake** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5f3E8y9xjcCREu6hAX:bnfp4nl)*

**Comment by ggould-tri** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/5#-:-L5nT7hT3ibYh9gm49uH:bnfp4nl)*

**Pull request merged**
