### PR TITLE
Merge google upstream as of 2020-05-18

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
In my own perusal, it seems like all of the relevant changes here are to the pyguide, and all of the pyguide changes are only formatting and wordsmithing -- except for one new module-level docstring section, to which I have added `class="nondrake"` to ignore it for now.  As such, I _think_ we probably only need two reviewers.

+@EricCousineau-TRI and +@SeanCurtis-TRI for review, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
I haven't looked at the moved shell styleguide nor the pylinter. I don't believe that's necessary but am open to arguments that suggest Drake reviewers *should* evaluate the linter. Perhaps so far as the "non-drake" portions go?

> Reviewed 6 of 9 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-:-MIyHuZq5Kf2jBD1LjMj:b5euigx)* status: 1 unresolved discussion, LGTM missing from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

___
*[pyguide.md, line 2057 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-MIyGBAB6qXTT5lXIOn9:-MIyGBACDod_H6ELo9MP:bsjjs0a) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f67fc57978c33328110a7bffd4051d8aa37f2834/pyguide.md#L2057)):*
> ```Markdown
>     consistent with the rest of the file).
> 
>     The description should include required type(s) if the code does not contain
> ```

nit: Same sentence twice -- is that a merge error or in the source?

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

We currently reference upstream GSG for shell, not Drake fork. Made a comment below about it.

> Reviewed 8 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-:-MIyRm9e5O1zsdZ_bA8P:b-7fmsrn)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

___
*[pyguide.md, line 2330 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-MIyOeH4AMs6CWA77Y-2:-MIyOeH4AMs6CWA77Y-3:bgrkeeo) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f67fc57978c33328110a7bffd4051d8aa37f2834/pyguide.md#L2330)):*
> ```Markdown
> If you need to avoid embedding extra space in the string, use either
> concatenated single-line strings or a multi-line string with
> [`textwrap.dedent()`](https://docs.python.org/3/library/textwrap.html#textwrap.dedent)
> ```

BTW Yay!
___
*[shellguide.md, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-MIySNiV57sSzJEZ8MW3:-MIySNiV57sSzJEZ8MW4:b-3i8gqz) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f67fc57978c33328110a7bffd4051d8aa37f2834/shellguide.md#L1)):*
> ```Markdown
>  https://google.github.io/styleguide/shell.xml

Do we care?

**Review by jwnimmer-tri — COMMENTED** [review]
> ... I haven't looked at the moved shell styleguide nor the pylinter ...

My mental model here is that the `styleguide` repository has a lot of dead code (and dead docs) in terms of Drake.  Upstream has many files that we don't use, but we keep them around in the repository here to make merging easier.  Only files opted-into by Drake are in scope for review.

In that light, `pylintrc` is out of scope, because we don't opt-in to it -- none of our tools use it, and none of the docs mention it.

I _thought_ that also meant that the shell style guide was out of scope, because I had completely forgotten that we cite the GSG shell styleguide as our law!  I wonder how many platform reviewers cross-check it (I'm sure I've failed to do so a few times).  I'll need to revisit this PR myself in that light.  Stay tuned.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-:-MIyogJGEPXONjdwimvX:bvorwb5)* status: 2 unresolved discussions, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
I think at this point, I am personally content with having Drake point to the unpinned upstream Shell Guide without ever vetting the ongoing changes there.  If we find something there objectionable, we could add it to `code_style_guide.rst` a specific exemption, or even take on the work of a fork if its serious.  But because we have little enough shell code in the tree, it doesn't seem worth investing too heavily in customizing the guide.

WDYT?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-:-MIzN4aI9zFqxGy4CXTV:b-igaha9)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

___
*[pyguide.md, line 2057 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-MIyGBAB6qXTT5lXIOn9:-MIzMo-B4Y3hFmkK7OSo:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f67fc57978c33328110a7bffd4051d8aa37f2834/pyguide.md#L2057)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

nit: Same sentence twice -- is that a merge error or in the source?
</blockquote></details>

Done.
___
*[shellguide.md, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-MIySNiV57sSzJEZ8MW3:-MIzNOovCe-EOt81-fVu:bybbkec) ([raw file](https://github.com/robotlocomotion/styleguide/blob/f67fc57978c33328110a7bffd4051d8aa37f2834/shellguide.md#L1)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Our current website links directly to GSG, not our fork of GSG:
https://drake.mit.edu/code_style_guide.html#shell-script-style
--> https://google.github.io/styleguide/shell.xml

Do we care?
</blockquote></details>

OK See response atop the PR.

**Review by EricCousineau-TRI — COMMENTED** [review]
SGTM.

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-:-MIzOmgR-xaoeL09GCH8:b-81nlyc)* status: LGTM missing from assignee SeanCurtis-TRI(platform)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I agree. 

:LGTM:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/36#-:-MIzQriC-jaSC30zZrtR:b-8wb09e)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
