### PR TITLE
pyguide: Add "for Drake" to title

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This matches how we do the C++ guide -- to clarify that it's a fork of upstream.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/43)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for all reviews, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: - thanks!

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/43#-:-MVqBWiNDIU5zp7n1jbc:b-hidk3u)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
Hm... forgot we have two reviewers necessary for this. I also don't have bits to admin-merge.

+@seancurtis-tri for add'l review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/43#-:-MVqBxRL5eulCsMxGiwf:b-nwmkoc)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/43#-:-MVqDdcw27c-DdQUpWsj:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @SeanCurtis-TRI)

**Pull request merged**
