### PR TITLE
Update README with new preview and pull request instructions

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
Revert the now-unused preview code and supporting files.

Relates https://github.com/RobotLocomotion/drake/pull/14803.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/44)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for first review, please.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: - thanks!

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/44#-:-MYfPlClArXaybfChVcF:b-hidk3u)* status: needs at least two assigned reviewers (waiting on @jwnimmer-tri)

**Comment by jwnimmer-tri** [comment]
+@SeanCurtis-TRI for platform review per schedule, please.

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/44#-:-MYfiqM439-K4GSmQ6Jo:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform) (waiting on @jwnimmer-tri)

**Pull request merged**
