### PR TITLE
cpplint: Add build/pragma_once checker

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This check is opt-in (disabled by default).

Relates to issue RobotLocomotion/drake#9516.
Tested in PR RobotLocomotion/drake#9769.

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/14)

### CODE REVIEW

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI for feature review, please.

**Review by EricCousineau-TRI — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/14#-:-LPWpMFU-UUTVCdtZ8i8:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri]

**Comment by jwnimmer-tri** [comment]
+@ggould-tri for platform review, please.  I know you're not on call tomorrow either, but I think it makes sense for you to look at this as well.  If you can't do it within a week or so, just let me know.

**Review by ggould-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/14#-:-LPX2cyT4JRibmafPhvg:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [ericcousineau-tri, ggould-tri]

**Pull request merged**
