### PR TITLE
cppguide: Clarify use of DRAKE_DEPRECATED

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Connects to the following: https://drake.mit.edu/code_review_checklist.html#is-the-code-the-minimal-set-of-what-you-want

Pulling example `git query` from: https://github.com/RobotLocomotion/drake/pull/14546#pullrequestreview-573818469

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
Came across this while re-reading style guide as part of my platform reviewer day.

+@jwnimmer-tri and +@seancurtis-tri for initial review, please!

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTb2Qhg29Fid2Ib_hX3:bqqbcwj)* status: LGTM missing from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform) (waiting on @jwnimmer-tri and @SeanCurtis-TRI)

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTb8e1o5s78Mj-LdC7g:bnfp4nl)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTb9KMX6oWyU1-88R6B:bmxilld)* status: :shipit: complete! all discussions resolved, LGTM from assignees jwnimmer-tri(platform),SeanCurtis-TRI(platform)

**Review by EricCousineau-TRI — COMMENTED** [review]
Remaining platform reviewers, please!

+@RussTedrake
+@ggould-tri
+@rpoyner-tri
+@sammy-tri
+@sherm1
+@soonho-tri
+@sammy-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTbAhft6KqYrxPjZ8z2:b-fw8tnu)* status: LGTM missing from assignees RussTedrake(platform),ggould-tri(platform),rpoyner-tri(platform),sherm1(platform),soonho-tri(platform),sammy-tri(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

**Review by sherm1 — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTbVRyi0TubeIrZYALa:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),ggould-tri(platform),sammy-tri(platform),soonho-tri(platform),RussTedrake(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, and @soonho-tri)

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTber9c9t7rWTPIQeCj:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),RussTedrake(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, @sammy-tri, and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTbg6oxDOFn7hlN2mZR:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),RussTedrake(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, and @sammy-tri)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTcJFrR5tnc2wVkovR7:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform) (waiting on @ggould-tri, @rpoyner-tri, @RussTedrake, and @sammy-tri)

**Comment by jwnimmer-tri** [comment]
Removing -@sammy-tri (unavailable).

**Review by rpoyner-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/41#-:-MTfs566BR8eH4MWaFft:bnfp4nl)* status: :shipit: complete! all discussions resolved, LGTM from assignees rpoyner-tri(platform),ggould-tri(platform),jwnimmer-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @ggould-tri and @RussTedrake)

**Pull request merged**
