### PR TITLE
Merge google upstream as of 2020-09-21

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
+@EricCousineau-TRI for first review, please.  I've "FYI'd" the only relevant change (to my eye) inline below.

I'll tag a second reviewer once you're set.  (I don't think this one needs the whole crew.)

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-:-MJhwsUf0oAuxwfCZEkG:b-k260ml)* status: 1 unresolved discussion, LGTM missing from assignee EricCousineau-TRI(platform), needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJhuGCk-JGEFBrZinIK:-MJhuGCk-JGEFBrZinIL:b-lbbfxy) (no related file):*
Working

This will need a Drake PR to confirm that cpplint and its unit test still pass in Drake CI.  It does pass OK for me locally.

---
___
*[pyguide.md, line 2210 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJhw2CM7gL-OLMBkJ6v:-MJhw2CM7gL-OLMBkJ6w:b-rnh0al) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3ad3779ce6e7189ab3039ce9f2a35ce3df544218/pyguide.md#L2210)):*
> ```Markdown
> aptly described using a one-line docstring.
> 
> <a id="doc-function-args"></a>
> ```

FYI These edits (to docstring rules) are the only relevant change to the subset of the guide that we use.

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm: on Sec 3.8 for Python.

Skimmed other things, and completely ignored languages we currently don't use (C#, Lisp)

> Reviewed 5 of 6 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-:-MJiZvN4BWCR7pgoh7rb:b-cwzjl8)* status: 2 unresolved discussions, needs at least two assigned reviewers (waiting on @jwnimmer-tri)

___
*[pyguide.md, line 2218 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJiYUlN-xUdpRYVUNFI:-MJiYUlN-xUdpRYVUNFJ:btt01e6) ([raw file](https://github.com/robotlocomotion/styleguide/blob/63e985df2a459e5b8d8bd9420eaaee6537e83975/pyguide.md#L2218)):*
> ```Markdown
>     <span class="drake">79-character\*</span>
>     line, use a hanging
>     indent of 2 or 4 spaces more than the parameter name (be consistent with the
> ```

BTW The "more than the parameter name" just feels distracting, as the examples still seem consistent w/ my understanding... but meh.
___
*[pyguide.md, line 2249 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJiYfmzB3M-ukxN-eY9:-MJiYfmzB3M-ukxN-eYA:bp1zjjp) ([raw file](https://github.com/robotlocomotion/styleguide/blob/63e985df2a459e5b8d8bd9420eaaee6537e83975/pyguide.md#L2249)):*
> ```Markdown
>                           keys: Sequence[Union[bytes, str]],
>                           require_all_keys: bool = False,
> ) -> Mapping[bytes, Tuple[str]]:
> ```

nit Should we state somewhere that `typing` annotations are non-Drake (at present)?
It's semi-evident by the fact that we hide that section, but dunno what it looks like when that rule is evident in this example.

---

FTR I only really care about them atm for ML crap where you have stupidly weird tensors (and I want to decorate the function s.t. the typing is actually functional), or you're defining dataclasses. I don't care about auto-complete / IDE linting atm.
Opinion may change in the future...

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38)* status: 1 unresolved discussion, needs at least two assigned reviewers (waiting on @EricCousineau-TRI and @jwnimmer-tri)

___
*[pyguide.md, line 2218 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJiYUlN-xUdpRYVUNFI:-MJihvUE6Ne52msUsh5j:biisn9i) ([raw file](https://github.com/robotlocomotion/styleguide/blob/63e985df2a459e5b8d8bd9420eaaee6537e83975/pyguide.md#L2218)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

BTW The "more than the parameter name" just feels distracting, as the examples still seem consistent w/ my understanding... but meh.
</blockquote></details>

Yeah.  I figured minimizing diffs vs upstream is worth accepting some weird wording now and again.
___
*[pyguide.md, line 2249 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJiYfmzB3M-ukxN-eY9:-MJijof0-ui4c_tLoADR:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/63e985df2a459e5b8d8bd9420eaaee6537e83975/pyguide.md#L2249)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

nit Should we state somewhere that `typing` annotations are non-Drake (at present)?
It's semi-evident by the fact that we hide that section, but dunno what it looks like when that rule is evident in this example.

---

FTR I only really care about them atm for ML crap where you have stupidly weird tensors (and I want to decorate the function s.t. the typing is actually functional), or you're defining dataclasses. I don't care about auto-complete / IDE linting atm.
Opinion may change in the future...
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
+@SeanCurtis-TRI for platform review per schedule (Monday), please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-:-MJikZC0-mmG2PK3D_3j:bwucnue)* status: 1 unresolved discussion, LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI, @jwnimmer-tri, and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJhuGCk-JGEFBrZinIK:-MJikXu415BYZwX5S7Vo:bv0l38p) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Working

This will need a Drake PR to confirm that cpplint and its unit test still pass in Drake CI.  It does pass OK for me locally.
</blockquote></details>

Pending https://github.com/RobotLocomotion/drake/pull/14217

---

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @EricCousineau-TRI and @SeanCurtis-TRI)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-MJhuGCk-JGEFBrZinIK:-MJipSKs8rTkpCNFIkW4:b-5ruqx8) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Pending https://github.com/RobotLocomotion/drake/pull/14217
</blockquote></details>

Done.  All happy.

---

**Review by EricCousineau-TRI — COMMENTED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38)* status: LGTM missing from assignee SeanCurtis-TRI(platform) (waiting on @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — COMMENTED** [review]
I likewise rubber stamped C# and lisp.

:LGTM:

> Reviewed 5 of 6 files at r1, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/38#-:-MK0C5zM-6cQTQtEotbF:b-lwwr0k)* status: :shipit: complete! all discussions resolved, LGTM from assignees SeanCurtis-TRI(platform),EricCousineau-TRI(platform)

**Pull request merged**
