### PR TITLE
README: Clarify styleguide update policy for Drake

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for initial review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXK9_eTCK2LFpCB6z2i:b9dpbpu)* status: all discussions resolved, platform LGTM missing

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

___
*[README.md, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKB63J2q78roU6tiTj:-LXKB63KB1xZvksl8vvU:bnjetav) ([raw file](https://github.com/robotlocomotion/styleguide/blob/20131e54644605120706eee53bb95550eba4a65d/README.md#L103)):*
> ```Markdown
> 
> As above, once the `styleguide` PR lands, submit a PR to `drake` to bump its
> SHA.
> ```

This could be a tiny bit misleading.  If the upstream changes included code changes, then we need _right away_ to open a draft Drake PR to vet the styleguide draft PR, prior to merging the styleguide PR.  If we wait until this moment, it's too late.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: 1 unresolved discussion, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[README.md, line 103 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKB63J2q78roU6tiTj:-LXKE7HB5esHImB4GS_b:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/20131e54644605120706eee53bb95550eba4a65d/README.md#L103)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

This could be a tiny bit misleading.  If the upstream changes included code changes, then we need _right away_ to open a draft Drake PR to vet the styleguide draft PR, prior to merging the styleguide PR.  If we wait until this moment, it's too late.
</blockquote></details>

Done.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKEpDg0jTCvFIV7z09:bnfp4nl)* status: 2 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @EricCousineau-TRI)

___
*[README.md, line 111 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKE_ea2H32Vdn_0nJq:-LXKE_ea2H32Vdn_0nJr:bucrpwh) ([raw file](https://github.com/robotlocomotion/styleguide/blob/ad5fd0ae9e5589e4b8e5c61e6e375cad88eb50ff/README.md#L111)):*
> ```Markdown
> --------------
> 
> Whenever a change is made, be sure to submit a PR to `drake` to bump its SHA.
> ```

nit Consider more proper nouns for clarity:
"Whenever a change *to styleguide* is made"
"PR to drake to bump *the styleguide* SHA"
___
*[README.md, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKEV911AGFTanYw5cY:-LXKEV923-2nXFjqJfxB:b5t31u2) ([raw file](https://github.com/robotlocomotion/styleguide/blob/ad5fd0ae9e5589e4b8e5c61e6e375cad88eb50ff/README.md#L119)):*
> ```Markdown
> 
> As above, once the `styleguide` PR lands, submit a PR to `drake` to bump its
> SHA.
> ```

nit I'm not sure what this last sentence is trying to add to the discussion?

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

___
*[README.md, line 119 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKEV911AGFTanYw5cY:-LXKGxm29oHB4HBblnYo:b-breron) ([raw file](https://github.com/robotlocomotion/styleguide/blob/ad5fd0ae9e5589e4b8e5c61e6e375cad88eb50ff/README.md#L119)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

nit I'm not sure what this last sentence is trying to add to the discussion?
</blockquote></details>

OK Er, sorry, leftover cruft from r1...

**Review by EricCousineau-TRI — COMMENTED** [review]
Platform review request, please:
+@RussTedrake
+@soonho-tri
+@ggould-tri
+@sammy-tri
+@SeanCurtis-TRI
+@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKH90o0l2CFKunq6Ll:b53qzbs)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKKf33EN2PkNl26Ey5:bmxilld)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee soonho-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri] (waiting on @EricCousineau-TRI, @ggould-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[README.md, line 112 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKJnbd3is93du9zy1q:-LXKJnbe6wDOrGD_euda:bftgfek) ([raw file](https://github.com/robotlocomotion/styleguide/blob/5a1b617cd83ab0f16db17a1669be2f6f354788c2/README.md#L112)):*
> ```Markdown
> 
> Whenever a change to `styleguide` is made, be sure to submit a PR to `drake` to
> bump the `styleguide` SHA. PRs to `drake` should marked as `do not merge` until
> ```

nit: "...should __*be*__ marked..."
___
*[README.md, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKK4pO1Uh1amRJyyWP:-LXKK4pO1Uh1amRJyyWQ:b4zq92l) ([raw file](https://github.com/robotlocomotion/styleguide/blob/5a1b617cd83ab0f16db17a1669be2f6f354788c2/README.md#L113)):*
> ```Markdown
> Whenever a change to `styleguide` is made, be sure to submit a PR to `drake` to
> bump the `styleguide` SHA. PRs to `drake` should marked as `do not merge` until
> the `styleguide` PR is merged, and the SHA refers only to the `gh-pages`
> ```

BTW Having not played with updating the stylguide, this last statement vis a vis the SHA isn't clear to me. After merging the styleguide PR, does the drake PR SHA value change from its initial, in-review state?
___
*[README.md, line 116 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKKNJACzduwDGPipnt:-LXKKNJACzduwDGPipnu:bxzubxq) ([raw file](https://github.com/robotlocomotion/styleguide/blob/5a1b617cd83ab0f16db17a1669be2f6f354788c2/README.md#L116)):*
> ```Markdown
> branch.
> 
> If there are changes to code (e.g. `cpplint`), be sure the `drake` PR is
> ```

BTW Could we swap "changes to code" with "code changes"? I had to wrestle my mind to stop it reading `to code` as an infinitive verb.

**Review by SeanCurtis-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee soonho-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri] (waiting on @EricCousineau-TRI, @ggould-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

___
*[README.md, line 116 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKKNJACzduwDGPipnt:-LXKKl5D3Qy9eCsyrKIQ:beh8yzo) ([raw file](https://github.com/robotlocomotion/styleguide/blob/5a1b617cd83ab0f16db17a1669be2f6f354788c2/README.md#L116)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Could we swap "changes to code" with "code changes"? I had to wrestle my mind to stop it reading `to code` as an infinitive verb.
</blockquote></details>

BTW Alternatively, an adjective would help: "...changes to supporting code", etc.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKKz1z6RBUPCHU9HNB:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee soonho-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri] (waiting on @EricCousineau-TRI, @ggould-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee soonho-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri] (waiting on @ggould-tri, @RussTedrake, @sammy-tri, @SeanCurtis-TRI, @sherm1, and @soonho-tri)

___
*[README.md, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKK4pO1Uh1amRJyyWP:-LXKQ1Ks3Jx1as8NvHvQ:b5cr1x1) ([raw file](https://github.com/robotlocomotion/styleguide/blob/5a1b617cd83ab0f16db17a1669be2f6f354788c2/README.md#L113)):*
<details><summary><i>Previously, SeanCurtis-TRI (Sean Curtis) wrote…</i></summary><blockquote>

BTW Having not played with updating the stylguide, this last statement vis a vis the SHA isn't clear to me. After merging the styleguide PR, does the drake PR SHA value change from its initial, in-review state?
</blockquote></details>

Tried to make process more explicit. Does this look OK?

**Review by soonho-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKSvcu1bNi8v2GLFnR:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri] (waiting on @ggould-tri, @RussTedrake, @sammy-tri, and @sherm1)

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri] (waiting on @ggould-tri, @RussTedrake, @sammy-tri, and @sherm1)

**Review by SeanCurtis-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri] (waiting on @ggould-tri, @RussTedrake, @sammy-tri, and @sherm1)

___
*[README.md, line 113 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-LXKK4pO1Uh1amRJyyWP:-LXKUWhs5FC5ZM86tjKl:b5k8wrr) ([raw file](https://github.com/robotlocomotion/styleguide/blob/5a1b617cd83ab0f16db17a1669be2f6f354788c2/README.md#L113)):*
<details><summary><i>Previously, EricCousineau-TRI (Eric Cousineau) wrote…</i></summary><blockquote>

Tried to make process more explicit. Does this look OK?
</blockquote></details>

Beautiful. Thanks.

**Review by ggould-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKWhQz-OQKwj7tLj8_:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee sammy-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri, ggould-tri] (waiting on @ggould-tri, @RussTedrake, @sammy-tri, and @sherm1)

**Review by sammy-tri — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: all discussions resolved, LGTM missing from assignee sammy-tri, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri, ggould-tri] (waiting on @ggould-tri, @RussTedrake, and @sherm1)

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXKd0dL8-ijCks78vi9:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee sherm1, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri, ggould-tri, sammy-tri] (waiting on @ggould-tri, @RussTedrake, and @sherm1)

**Review by sherm1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXLtfop45WlXjdY6MvI:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri, ggould-tri, sammy-tri, sherm1] (waiting on @ggould-tri and @RussTedrake)

**Review by jwnimmer-tri — COMMENTED** [review]
I think we probably don't need -@RussTedrake on this one, since it's more a matter of tactics, not policy.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19#-:-LXLzTa53HwIMo_5zLQc:b-mibfyt)* status: all discussions resolved, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri, ggould-tri, sammy-tri, sherm1] (waiting on @ggould-tri and @RussTedrake)

**Review by soonho-tri — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/19)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, seancurtis-tri, soonho-tri, ggould-tri, sammy-tri, sherm1] (waiting on @ggould-tri)

**Pull request merged**
