### PR TITLE
cppguide: Add note on preference of `internal` namespaces

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
Relates https://github.com/RobotLocomotion/drake/issues/10210

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for initial review, please.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LX5Y5Wi5CcAo5a81jD-:b9dpbpu)* status: all discussions resolved, platform LGTM missing

**Review by jwnimmer-tri — CHANGES_REQUESTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @EricCousineau-TRI)

___
*[cppguide.html, line 4918 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LX688NV-eMDG_nIELdE:-LX688NV-eMDG_nIELdF:buc6d0s) ([raw file](https://github.com/robotlocomotion/styleguide/blob/06a1f56b1a0b1d2530935d2064b026749357d257/cppguide.html#L4918)):*
> ```HTML
> internal name is helpful
> (<code>websearch::index::frobber_internal</code> for use
> in <code>frobber.h</code>)</p>
> ```

Rather than add a confusing caveat in the next paragraph ("even if it causes collisions" -- I didn't understand it at all when I first read it), perhaps instead we could just drake-strikethrough this entire prior paragraph?
___
*[cppguide.html, line 4923 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LX68Mh4-8DpNML09XdC:-LX68Mh4-8DpNML09XdD:b-4yiaa1) ([raw file](https://github.com/robotlocomotion/styleguide/blob/06a1f56b1a0b1d2530935d2064b026749357d257/cppguide.html#L4923)):*
> ```HTML
> <code>detail</code>, even if it causes collisions. If a file is wholly
> dedicated to internal implementation details, consider placing it under a
> folder named <code>internal/</code> (unless it causes migration issues).</p>
> ```

I don't think the second sentence here should rise to the level of a consensus recommendation (or at least not yet).

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18)* status: 2 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jwnimmer-tri)

___
*[cppguide.html, line 4918 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LX688NV-eMDG_nIELdE:-LX6XsG3E6rIRRYc9KIR:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/06a1f56b1a0b1d2530935d2064b026749357d257/cppguide.html#L4918)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Rather than add a confusing caveat in the next paragraph ("even if it causes collisions" -- I didn't understand it at all when I first read it), perhaps instead we could just drake-strikethrough this entire prior paragraph?
</blockquote></details>

Done.
___
*[cppguide.html, line 4923 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LX68Mh4-8DpNML09XdC:-LX6XsWV-eZctHKfqnEp:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/06a1f56b1a0b1d2530935d2064b026749357d257/cppguide.html#L4923)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

I don't think the second sentence here should rise to the level of a consensus recommendation (or at least not yet).
</blockquote></details>

Done.

**Review by jwnimmer-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LX6ZIAW1y27QaWZcwm_:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

**Review by sherm1 — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LX6bNzdDjB6lAqUC08o:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, sherm1]

**Review by EricCousineau-TRI — COMMENTED** [review]
Platform review request, please:
+@RussTedrake
+@soonho-tri 
+@ggould-tri
+@sammy-tri
+@SeanCurtis-TRI
+@sherm1

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LX6k0s2194zE8BmISQO:b-knkbrs)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, sherm1]

**Review by soonho-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LX6tI-j3p0VoCY_IMqn:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee seancurtis-tri, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri] (waiting on @ggould-tri, @RussTedrake, @sammy-tri, and @SeanCurtis-TRI)

**Review by SeanCurtis-TRI — APPROVED** [review]
:LGTM:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LX7Gil20ggZ4otNUxoa:bmxilld)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, LGTM missing from assignee russtedrake, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri] (waiting on @ggould-tri, @RussTedrake, and @sammy-tri)

**Review by RussTedrake — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LXBEv78Bgu4m5BKGkn7:bnfp4nl)* status: 1 unresolved discussion, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri, russtedrake] (waiting on @EricCousineau-TRI, @ggould-tri, and @sammy-tri)

___
*[cppguide.html, line 4923 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LXBExERBLUAamcqrD1i:-LXBExERBLUAamcqrD1j:b2gu6n1) ([raw file](https://github.com/robotlocomotion/styleguide/blob/ca50728c16bf550777cbbeb028548b54ef6d7f4a/cppguide.html#L4923)):*
> ```HTML
> 
> <p class="drake">Prefer just the name <code>internal</code>. For consistency,
> avoid using the name <code>detail</code>.</p>
> ```

nit, the specific words you've chosen "prefer *just* the ..." appear to be directly in conflict with the advice from the paragraph above.  Perhaps "Prefer the name/postfix *internal*".

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri, russtedrake] (waiting on @ggould-tri and @sammy-tri)

___
*[cppguide.html, line 4923 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LXBExERBLUAamcqrD1i:-LXFYpafAKDnVRV4TLw2:bubfndm) ([raw file](https://github.com/robotlocomotion/styleguide/blob/ca50728c16bf550777cbbeb028548b54ef6d7f4a/cppguide.html#L4923)):*
<details><summary><i>Previously, RussTedrake (Russ Tedrake) wrote…</i></summary><blockquote>

nit, the specific words you've chosen "prefer *just* the ..." appear to be directly in conflict with the advice from the paragraph above.  Perhaps "Prefer the name/postfix *internal*".
</blockquote></details>

OK Yup, that's why the paragraph above is in ~strikethrough~ (aka nondrake).

**Review by RussTedrake — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18)* status: all discussions resolved, LGTM missing from assignee ggould-tri, LGTM missing from assignee sammy-tri, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri, russtedrake] (waiting on @ggould-tri and @sammy-tri)

___
*[cppguide.html, line 4923 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-LXBExERBLUAamcqrD1i:-LXFv3LL1U9sNSHVWuoS:bdrun8v) ([raw file](https://github.com/robotlocomotion/styleguide/blob/ca50728c16bf550777cbbeb028548b54ef6d7f4a/cppguide.html#L4923)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

OK Yup, that's why the paragraph above is in ~strikethrough~ (aka nondrake).
</blockquote></details>

my bad. did not realize <nondrake> => strikethrough, but that makes sense.

**Review by sammy-tri — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LXJvEWJ7iYf2TcgsGDW:bnfp4nl)* status: all discussions resolved, LGTM missing from assignee ggould-tri, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri, russtedrake, sammy-tri] (waiting on @ggould-tri)

**Review by SeanCurtis-TRI — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18)* status: all discussions resolved, LGTM missing from assignee ggould-tri, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri, russtedrake, sammy-tri] (waiting on @ggould-tri)

**Review by ggould-tri — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/18#-:-LXK2FIz9Yvqw2x-qCVw:bnfp4nl)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri, sherm1, soonho-tri, seancurtis-tri, russtedrake, sammy-tri, ggould-tri] (waiting on @ggould-tri)

**Pull request merged**
