### PR TITLE
Merge google upstream as of 2020-09-25

### PR DESCRIPTION
**Pull request by jwnimmer-tri**
For a preview [click here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/google-merge-2020-09-25/cppguide.html).

---
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39)

### CODE REVIEW

**Review by jwnimmer-tri — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39)* status: needs platform reviewer assigned, needs at least two assigned reviewers

___
*[cppguide.html, line 276 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-MK0fGo35XMWuk9D3sve:-MK0fGo42o_HAhNUn9Ah:b-doaqb6) ([raw file](https://github.com/robotlocomotion/styleguide/blob/228fb1a158a990d85accd256fd608313cf5a1493/cppguide.html#L276)):*
> ```HTML
> </p>
> 
> <h3 id="Include_What_You_Use">Include What You Use</h3>
> ```

FYI This section was factored out upstream as its own standalone topic.  Previously, this text was in the "Names and Order of Includes", including Drake's exception.

**Comment by jwnimmer-tri** [comment]
+@EricCousineau-TRI
+@RussTedrake
+@SeanCurtis-TRI
+@ggould-tri
+@rpoyner-tri
+@sammy-tri
+@sherm1
+@soonho-tri
for review, please.

For a preview [click here](http://htmlpreview.github.io/?https://raw.githubusercontent.com/jwnimmer-tri/styleguide/google-merge-2020-09-25/cppguide.html).

The changes here are mostly just copy-editing, but there are enough small non-trivial changes that I think this merits a review offer to the full crew.

You are invited to read this as closely or loosely as your time merits. I'll leave this open for this week (until Oct 23rd) and resolve any discussions you open during that period, but then I'll plan to merge after that point. We can continue revising the guide in follow-ups as necessary.

**Review by ggould-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK0osTP9vSKQAguoWdz:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),sherm1(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @SeanCurtis-TRI, @sherm1, and @soonho-tri)

___
*[cppguide.html, line 3835 at r3](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-MK0oLr83EK9qBHFQzpm:-MK0oLr83EK9qBHFQzpn:bvdbbkz) ([raw file](https://github.com/robotlocomotion/styleguide/blob/228fb1a158a990d85accd256fd608313cf5a1493/cppguide.html#L3835)):*
> ```HTML
>   In such situations, it's often possible to define local variables with
>   explicit types that convey the relevant information:
>   </p><pre class="goodcode">if (auto it = my_map_.find(key); it != my_map_.end()) {
> ```

FYI Neat!  I didn't realize this was allowed!

**Review by sherm1 — COMMENTED** [review]
:lgtm: 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK0rQYH1g1ZNddCtkG4:bg7igkv)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),SeanCurtis-TRI(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @SeanCurtis-TRI, @sherm1, and @soonho-tri)

**Review by SeanCurtis-TRI — COMMENTED** [review]
:LGTM:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK0s3172XABBi10O00z:bmxilld)* status: LGTM missing from assignees rpoyner-tri(platform),sammy-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sammy-tri, @sherm1, and @soonho-tri)

**Review by sammy-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK1_wA3BWEQCdvyEL-U:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),soonho-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, @sherm1, and @soonho-tri)

**Review by soonho-tri — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK1atbY-Mu5ONA-q0I3:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),EricCousineau-TRI(platform),RussTedrake(platform) (waiting on @EricCousineau-TRI, @rpoyner-tri, @RussTedrake, and @sherm1)

**Review by EricCousineau-TRI — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK1e_Aq6L5-nay5CADS:bnfp4nl)* status: LGTM missing from assignees rpoyner-tri(platform),RussTedrake(platform) (waiting on @rpoyner-tri, @RussTedrake, and @sherm1)

**Review by RussTedrake — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/39#-:-MK1z3QM2Qob48kwdX3P:bg7igk9)* status: LGTM missing from assignee rpoyner-tri(platform) (waiting on @rpoyner-tri, @RussTedrake, and @sherm1)

**Comment by jwnimmer-tri** [comment]
The review deadline has expired, I'm merging now. I am happy to adjust to late feedback in a separate PR.

-@rpoyner-tri

**Pull request merged**
