### PR TITLE
Add script to preview locally

### PR DESCRIPTION
**Pull request by EricCousineau-TRI**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23)

### CODE REVIEW

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jamiesnape for review, please.

\cc @jwnimmer-tri 

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QW0ER3b6lYo7PAVYs:bnrvff9)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
I don't have an issue with committing a Gemfile to the root of the repository as is customary. It's not like we are going to use Ruby for anything else.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QWOee1XjXdt1kPmCr:b-ijcazz)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

**Review by jamiesnape — COMMENTED** [review]
Also, you can commit `_config.yml` if the intent is to have local and remote be identical.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QXMtxB0awePBzGA_8:b-cr1xgy)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

**Comment by jwnimmer-tri** [comment]
The preview tool should write to a tmpdir (which can be a single subdir within the source tree, if needed); it must not write to `$HOME`.  It's okay to rely on (request) `apt` commands from the user.

**Comment by EricCousineau-TRI** [comment]
Then intent is to have local and remote identical, but I don't have the time to fully figure out how to mirror GitHub's theme / style. I'd prefer not to commit either the Gemfile nor the config, as I don't know how it will affect GitHub generation.
I will add a TODO.

I will also update to write to a tmpdir.

**Review by jamiesnape — COMMENTED** [review]
I just think this should be a three line or so shell script. Something like

gem install --install-dir vendor something
bundle install --path vendor something
bundle exec something

They (GitHub) even suggest creating a Gemfile one in the instructions.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QXjFB7XKhiSnCSIKF:b-ozywq0)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

___
*[.gitignore, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QXqGK9R1A9gE0N_Gw:-M-QXqGK9R1A9gE0N_Gx:b3kw2l2) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3cbd70805a18c7b9359cf5b90dff1c01c32d17a0/.gitignore#L9)):*
> ```ignore
> 
> # Generated by Jekyll build.
> /_site/
> ```

FYI https://github.com/github/gitignore/blob/master/Jekyll.gitignore

**Review by EricCousineau-TRI — COMMENTED** [review]
I don't want `${GEM_HOME}/bin` to be on the user's PATH by default via `~/.bashrc` / `~/.bash_aliases` (which is required to use `bundle`), and I'd prefer to make it a one-step for now. We can revisit later?

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-Q_qGqB8Zvy9a38os_:b-3nvkk2)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

___
*[.gitignore, line 9 at r1](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QXqGK9R1A9gE0N_Gw:-M-QaKYN218wQrwo1Gyw:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/3cbd70805a18c7b9359cf5b90dff1c01c32d17a0/.gitignore#L9)):*
<details><summary><i>Previously, jamiesnape (Jamie Snape) wrote…</i></summary><blockquote>

FYI https://github.com/github/gitignore/blob/master/Jekyll.gitignore
</blockquote></details>

Done.

**Review by jamiesnape — COMMENTED** [review]
I don't think that is actually true (I have never done any of that), but yes, we can revisit.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QaY398BMNgxSYHiUp:b-weyi3a)* status: all discussions resolved, LGTM missing from assignee jamiesnape, platform LGTM missing (waiting on @jamiesnape)

**Review by jamiesnape — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-Qatf7EkGGpthSmdfL:bnfp4nl)* status: all discussions resolved, platform LGTM missing (waiting on @jamiesnape)

**Review by EricCousineau-TRI — COMMENTED** [review]
+@jwnimmer-tri for platform please

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QdMT06VqY6I3ET8z2:b-1t4l8z)* status: all discussions resolved, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @jamiesnape and @jwnimmer-tri)

**Review by jwnimmer-tri — COMMENTED** [review]
Checkpoint from local testing.

> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-QtmKGAj5mzpvPdgCt:b-v8k7nu)* status: 3 unresolved discussions, LGTM missing from assignee jwnimmer-tri, platform LGTM missing (waiting on @EricCousineau-TRI, @jamiesnape, and @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-Qt-_e-44sKQ5xwAML:-M-Qt-_e-44sKQ5xwAMM:b7ifaw) (no related file):*
Since the README does not link to pyguide at all, I think we need docstring or print statement or something to tell us to open `http://127.0.0.1:4000/pyguide.html` as the thing we want to preview.  Best guess is that near the new README.md text is what we want.

---
___
*[preview_site_jekyll.py, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QqkdV2A42fMKaRR2p:-M-QqkdV2A42fMKaRR2q:b47j7gy) ([raw file](https://github.com/robotlocomotion/styleguide/blob/df7d6c8448e8f831de5c79fa2949e23459151edc/preview_site_jekyll.py#L17)):*
> ```Python
> Missing prerequisites. Please run:
> 
>     sudo apt install ruby-full build-essential zlib1g-dev
> ```

The preview failed for me, because I had ruby installed but not ruby-full -- so `which gem` passed but `bundle update` failed.  (I think because ruby-dev was missing.)
___
*[preview_site_jekyll.py, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QsfAD11sJaLXdv6LI:-M-QsfAD11sJaLXdv6LJ:bnz0ntg) ([raw file](https://github.com/robotlocomotion/styleguide/blob/df7d6c8448e8f831de5c79fa2949e23459151edc/preview_site_jekyll.py#L62)):*
> ```Python
>     if gem_bin not in path:
>         path.insert(0, gem_bin)
>     env["PATH"] = ":".join(path)
> ```

Needs `env["HOME"] = "/does/not/exist"` here to prevent it from writing to my homedir.

**Review by jwnimmer-tri — COMMENTED** [review]
:lgtm: platform modulo discussions.

> Reviewed 1 of 3 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-:-M-Quxce4BuW3-WT94bE:bk294kv)* status: 3 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @EricCousineau-TRI)

___
*[.gitignore, line 1 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QuHoM2gj5dcgRk-YN:-M-QuHoM2gj5dcgRk-YO:bhakr9k) ([raw file](https://github.com/robotlocomotion/styleguide/blob/df7d6c8448e8f831de5c79fa2949e23459151edc/.gitignore#L1)):*
> ```ignore
> # Generated by `preview_site_jekyll.py`
> ```

FYI In an ideal world, either all of the shrapnel goes into a single "build/" folder that is easy to nuke, or the preview script deletes the shrapnel prior to exiting.  Having mold growing in my source tree is not ideal.

**Review by EricCousineau-TRI — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23)* status: 3 unresolved discussions, platform LGTM from [jwnimmer-tri] (waiting on @jwnimmer-tri)

*[a discussion](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-Qt-_e-44sKQ5xwAML:-M-R99UgA-gtxczn9_kq:b-896fix) (no related file):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Since the README does not link to pyguide at all, I think we need docstring or print statement or something to tell us to open `http://127.0.0.1:4000/pyguide.html` as the thing we want to preview.  Best guess is that near the new README.md text is what we want.
</blockquote></details>

Done.

---
___
*[preview_site_jekyll.py, line 17 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QqkdV2A42fMKaRR2p:-M-R92ez4u798m6WV74m:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/df7d6c8448e8f831de5c79fa2949e23459151edc/preview_site_jekyll.py#L17)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

The preview failed for me, because I had ruby installed but not ruby-full -- so `which gem` passed but `bundle update` failed.  (I think because ruby-dev was missing.)
</blockquote></details>

Done.
___
*[preview_site_jekyll.py, line 62 at r2](https://reviewable.io/reviews/robotlocomotion/styleguide/23#-M-QsfAD11sJaLXdv6LI:-M-R955GBp_ro99LV4-A:b-896fix) ([raw file](https://github.com/robotlocomotion/styleguide/blob/df7d6c8448e8f831de5c79fa2949e23459151edc/preview_site_jekyll.py#L62)):*
<details><summary><i>Previously, jwnimmer-tri (Jeremy Nimmer) wrote…</i></summary><blockquote>

Needs `env["HOME"] = "/does/not/exist"` here to prevent it from writing to my homedir.
</blockquote></details>

Done.

**Review by jwnimmer-tri — COMMENTED** [review]
> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/23)* status: :shipit: complete! all discussions resolved, platform LGTM from [jwnimmer-tri]

**Pull request merged**
