### PR TITLE
Merge latest upstream; no changes to Drake styleguide content

### PR DESCRIPTION
**Pull request by ggould-tri**
This change is [Reviewable](https://reviewable.io/reviews/robotlocomotion/styleguide/4)

### CODE REVIEW

**Comment by ggould-tri** [comment]
+@seancurtis-tri for all review (this is all just upstream content merged to our stuff).  No changes to the C++ style guide but the cpplint changes will be real to us if drake updates its workspace sha.

---

Review status: 0 of 6 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/4#-:-L2WaIplM_saS_JgLK9x:b8ei4za)*

**Comment by jwnimmer-tri** [comment]
(FWIW, in general I think we should bump Drake to use the tip of this repository without delay.)

**Comment by SeanCurtis-TRI** [comment]
:LGTM: FOr both

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/robotlocomotion/styleguide/4#-:-L2WyvWNjAR2pHfJ0a8a:b-r3t4ih)*

**Comment by jwnimmer-tri** [comment]
It looks like this was a squash-merge (egads!).  My guess is that we'll probably have to force-push and rewrite history to resolve it.  @EricCousineau-TRI is going to open an issue where we can discuss and decide a plan.  We'll probably want to disable squash-merge in the Settings tab for this repository, also.  Stay tuned.

**Comment by EricCousineau-TRI** [comment]
Filed issue: RobotLocomotion/drake#8638

On top of that, it wasn't a rebase, so we'll want to make sure the instructions are clear as well - whether we keep up-to-date with no-squash merges, or truly want to stick to rebases to consolidate our changes but suffer from history rewrites for each update (which is what I do for `pybind11`, and TBH isn't all that bad).

**Pull request merged**
